Repository ThatConference/that-api-sessions, pull requests merged in 2021-05, with the labels that each got.

#132 typo fixes
  package-lock.json
  package.json
  src/graphql/typeDefs/dataTypes/interfaces/base.graphql
  src/graphql/typeDefs/dataTypes/session/keynote.graphql
  src/graphql/typeDefs/dataTypes/session/openSpace.graphql
  src/graphql/typeDefs/dataTypes/session/panel.graphql
  src/graphql/typeDefs/dataTypes/session/regular.graphql
  src/graphql/typeDefs/dataTypes/session/workshop.graphql
Labels: Chore, bug, dependencies

#133 adding enum descriptions for the ui
  src/graphql/typeDefs/dataTypes/enums/assetLinkType.graphql
  src/graphql/typeDefs/dataTypes/enums/category.graphql
  src/graphql/typeDefs/dataTypes/enums/entityType.graphql
  src/graphql/typeDefs/dataTypes/enums/mentorship.graphql
  src/graphql/typeDefs/dataTypes/enums/sessionCategory.graphql
  src/graphql/typeDefs/dataTypes/enums/sessionFilter.graphql
  src/graphql/typeDefs/dataTypes/enums/sessionType.graphql
  src/graphql/typeDefs/dataTypes/enums/status.graphql
  src/graphql/typeDefs/dataTypes/enums/targetAudience.graphql
Labels: enhancement

#134 change session name parameter with `session`
  src/graphql/resolvers/mutations/adminSessionCreate.js
  src/graphql/resolvers/mutations/adminSessionUpdate.js
  src/graphql/resolvers/mutations/sessionCreate.js
  src/graphql/resolvers/mutations/sessionUpdate.js
  src/graphql/typeDefs/mutations/adminSessionCreate.graphql
  src/graphql/typeDefs/mutations/adminSessionUpdate.graphql
  src/graphql/typeDefs/mutations/sessionCreate.graphql
  src/graphql/typeDefs/mutations/sessionUpdate.graphql
Labels: enhancement

#135 CFP and Schedule updates
  src/dataSources/cloudFirestore/session.js
  src/graphql/resolvers/queries/adminSessions.js
  src/graphql/resolvers/queries/index.js
  src/graphql/resolvers/queries/keynote.js
  src/graphql/resolvers/queries/openSpace.js
  src/graphql/resolvers/queries/panel.js
  src/graphql/resolvers/queries/regular.js
  src/graphql/resolvers/queries/sessionAdminFields.js
  src/graphql/resolvers/queries/sessions.js
  src/graphql/resolvers/queries/theSessions.js
  src/graphql/resolvers/queries/workshop.js
  src/graphql/typeDefs/dataTypes/enums/targetLocation.graphql
  src/graphql/typeDefs/dataTypes/inputs/keynoteInput.graphql
  src/graphql/typeDefs/dataTypes/inputs/openSpaceInput.graphql
  src/graphql/typeDefs/dataTypes/inputs/panelInput.graphql
  src/graphql/typeDefs/dataTypes/inputs/workshopInput.graphql
  src/graphql/typeDefs/dataTypes/interfaces/base.graphql
  src/graphql/typeDefs/dataTypes/interfaces/eyesFront.graphql
  src/graphql/typeDefs/dataTypes/session/acceptedSession.graphql
  src/graphql/typeDefs/dataTypes/session/keynote.graphql
  src/graphql/typeDefs/dataTypes/session/mySession.graphql
  src/graphql/typeDefs/dataTypes/session/openSpace.graphql
  src/graphql/typeDefs/dataTypes/session/panel.graphql
  src/graphql/typeDefs/dataTypes/session/regular.graphql
  src/graphql/typeDefs/dataTypes/session/sessionAdminFields.graphql
  src/graphql/typeDefs/dataTypes/session/workshop.graphql
  src/graphql/typeDefs/queries/adminSessions.graphql
  src/graphql/typeDefs/queries/sessionsQuery.graphql
Labels: enhancement

#136 More schedule and CFP session api updates
  src/dataSources/cloudFirestore/session.js
  src/graphql/resolvers/mutations/adminSessions.js
  src/graphql/typeDefs/dataTypes/admin/keynoteAdminInput.graphql
  src/graphql/typeDefs/dataTypes/admin/openSpaceAdminInput.graphql
  src/graphql/typeDefs/dataTypes/admin/panelAdminInput.graphql
  src/graphql/typeDefs/dataTypes/admin/scheduleInput.graphql
  src/graphql/typeDefs/dataTypes/admin/workshopAdminInput.graphql
  src/graphql/typeDefs/dataTypes/enums/sessionCategory.graphql
  src/graphql/typeDefs/dataTypes/enums/sessionType.graphql
  src/graphql/typeDefs/dataTypes/inputs/artificatInput.graphql
  src/graphql/typeDefs/dataTypes/inputs/assetAssignmentInput.graphql
  src/graphql/typeDefs/dataTypes/inputs/assetSetOwnerInput.graphql
  src/graphql/typeDefs/dataTypes/inputs/keynoteInput.graphql
  src/graphql/typeDefs/dataTypes/inputs/openSpaceInput.graphql
  src/graphql/typeDefs/dataTypes/inputs/panelInput.graphql
  src/graphql/typeDefs/dataTypes/inputs/regularInput.graphql
  src/graphql/typeDefs/dataTypes/inputs/workshopInput.graphql
  src/graphql/typeDefs/dataTypes/interfaces/base.graphql
  src/graphql/typeDefs/dataTypes/interfaces/eyesFront.graphql
  src/graphql/typeDefs/dataTypes/regularInput.graphql
  src/graphql/typeDefs/dataTypes/session/acceptedSession.graphql
  src/graphql/typeDefs/dataTypes/session/keynote.graphql
  src/graphql/typeDefs/dataTypes/session/mySession.graphql
  src/graphql/typeDefs/dataTypes/session/openSpace.graphql
  src/graphql/typeDefs/dataTypes/session/panel.graphql
  src/graphql/typeDefs/dataTypes/session/regular.graphql
  src/graphql/typeDefs/dataTypes/session/workshop.graphql
  src/graphql/typeDefs/mutations/adminSessions.graphql
Labels: enhancement

#137 update session enum for workshop and add duration to workshop type
  src/graphql/typeDefs/dataTypes/admin/workshopAdminInput.graphql
  src/graphql/typeDefs/dataTypes/enums/duration.graphql
  src/graphql/typeDefs/dataTypes/enums/sessionType.graphql
  src/graphql/typeDefs/dataTypes/inputs/workshopInput.graphql
  src/graphql/typeDefs/dataTypes/session/workshop.graphql
Labels: enhancement

#139 lock apollo packages version
  package-lock.json
  package.json
Labels: bug

#138 correct me/session return type, to TheSessions. Update AcceptedSession
  package-lock.json
  package.json
  src/graphql/resolvers/index.js
  src/graphql/resolvers/queries/theSessions.js
  src/graphql/typeDefs/dataTypes/admin/scheduleInput.graphql
  src/graphql/typeDefs/dataTypes/enums/sessionCategory.graphql
  src/graphql/typeDefs/dataTypes/enums/targetAudience.graphql
  src/graphql/typeDefs/dataTypes/session/acceptedSession.graphql
  src/graphql/typeDefs/queries/meQuery.graphql
  src/graphql/typeDefs/scalars.graphql
Labels: bug, enhancement

#140 Add eventId to update inputs
  src/graphql/typeDefs/dataTypes/admin/keynoteAdminInput.graphql
  src/graphql/typeDefs/dataTypes/admin/openSpaceAdminInput.graphql
  src/graphql/typeDefs/dataTypes/admin/panelAdminInput.graphql
  src/graphql/typeDefs/dataTypes/admin/regularAdminInput.graphql
  src/graphql/typeDefs/dataTypes/admin/workshopAdminInput.graphql
  src/graphql/typeDefs/dataTypes/inputs/keynoteInput.graphql
  src/graphql/typeDefs/dataTypes/inputs/panelInput.graphql
  src/graphql/typeDefs/dataTypes/inputs/regularInput.graphql
  src/graphql/typeDefs/dataTypes/inputs/workshopInput.graphql
Labels: bug

#142 clear protected fields from openspace to other type
  src/graphql/resolvers/mutations/sessionUpdate.js
Labels: bug, enhancement

#143 Correct typo referencing date scalar
  src/graphql/resolvers/index.js
Labels: bug

#145 initial removal of assets. moved to garage api
  package.json
  src/dataSources/cloudFirestore/asset.js
  src/graphql/index.js
  src/graphql/resolvers/mutations/asset.js
  src/graphql/resolvers/mutations/assets.js
  src/graphql/resolvers/mutations/index.js
  src/graphql/resolvers/mutations/root.js
  src/graphql/resolvers/queries/acceptedSession.js
  src/graphql/resolvers/queries/anonymizedSession.js
  src/graphql/resolvers/queries/asset.js
  src/graphql/resolvers/queries/assets.js
  src/graphql/resolvers/queries/entity.js
  src/graphql/resolvers/queries/index.js
  src/graphql/resolvers/queries/keynote.js
  src/graphql/resolvers/queries/mySession.js
  src/graphql/resolvers/queries/openSpace.js
  src/graphql/resolvers/queries/panel.js
  src/graphql/resolvers/queries/regular.js
  src/graphql/resolvers/queries/root.js
  src/graphql/resolvers/queries/workshop.js
  src/graphql/resolvers/shared/resolveSessionAssets.js
  src/graphql/typeDefs/dataTypes/asset.graphql
  src/graphql/typeDefs/dataTypes/assetAssignment.graphql
  src/graphql/typeDefs/dataTypes/assetLink.graphql
  src/graphql/typeDefs/dataTypes/enums/assetLinkType.graphql
  src/graphql/typeDefs/dataTypes/enums/entityType.graphql
  src/graphql/typeDefs/dataTypes/extendedTypes/extended-asset.graphql
  src/graphql/typeDefs/dataTypes/inputs/assetAssignmentInput.graphql
  src/graphql/typeDefs/dataTypes/inputs/assetInput.graphql
  src/graphql/typeDefs/dataTypes/inputs/assetLinkInput.graphql
  src/graphql/typeDefs/dataTypes/inputs/assetSetOwnerInput.graphql
  src/graphql/typeDefs/mutations/asset.graphql
  src/graphql/typeDefs/mutations/assets.graphql
  src/graphql/typeDefs/mutations/rootMutation.graphql
  src/graphql/typeDefs/queries/assetQuery.graphql
  src/graphql/typeDefs/queries/assetsQuery.graphql
  src/graphql/typeDefs/queries/rootQuery.graphql
  src/graphql/typeDefs/unions.graphql
Labels: Chore

#148 Hook up schedule batch updates
  package.json
  src/dataSources/cloudFirestore/session.js
  src/graphql/resolvers/mutations/adminSessions.js
Labels: enhancement
